import "./globals.css";
import type { Metadata } from "next";
import { Inter, Nunito, Roboto } from "next/font/google";
import { Header } from "./(site)/components/Header";
import { ThemeProvider } from "./components/themeProvider";
import { TanstackProvider } from "./components/TanstackProvider";
import { ToasterContext } from "./context/ToasterContext";

const inter = Inter({ subsets: ["latin"] });

const nunito = Nunito({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-nunito",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${nunito.variable} ${roboto.variable}`}>
      <body className={inter.className}>
        <TanstackProvider>
          <ToasterContext />
          <div className="px-16 flex flex-col gap-12 bg-white min-h-screen py-44 pb-16">
            <Header />

            {children}
          </div>
        </TanstackProvider>
      </body>
    </html>
  );
}
