import "./globals.css";

import type { Metadata } from "next";

import { GeistSans } from "geist/font/sans";
import { Nunito, Roboto } from "next/font/google";

import { Header } from "./(site)/_components/Header";

import { Toaster } from "@/components/ui/sonner";

const nunito = Nunito({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-nunito",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${nunito.variable} ${roboto.variable} ${GeistSans.className}`}
    >
      <body className={nunito.className}>
        <Toaster
          toastOptions={{
            classNames: {
              error: "group-[.toaster]:text-red-500",
              success: "group-[.toaster]:text-green-500",
            },
          }}
        />

        <div className="px-16 flex flex-col gap-12 bg-white min-h-screen py-44 pb-16">
          <Header />

          {children}
        </div>
      </body>
    </html>
  );
}
